#!/bin/bash

while :; do
( speaker-test -t sine -f 700 >/dev/null )& pid=$! ; sleep 0.05s ; kill -9 $pid
sleep 0.05
( speaker-test -t sine -f 800 >/dev/null )& pid=$! ; sleep 0.05s ; kill -9 $pid
sleep 0.05
( speaker-test -t sine -f 900 >/dev/null )& pid=$! ; sleep 0.05s ; kill -9 $pid
sleep 1
( speaker-test -t sine -f 700 >/dev/null )& pid=$! ; sleep 0.05s ; kill -9 $pid
sleep 0.05
( speaker-test -t sine -f 800 >/dev/null )& pid=$! ; sleep 0.05s ; kill -9 $pid
sleep 0.05
( speaker-test -t sine -f 900 >/dev/null )& pid=$! ; sleep 0.05s ; kill -9 $pid
sleep 3
done 2>/dev/null
